" designed for vim 8+
"
" I'm going to add some things that need turned on and off often

"
"     EDITING STUFF
set nogdefault  " this affects search :s///g (subst. all)
set js " this inserts 2 spaces after . or ? or !
set showmatch
" set nowrap
set linebreak
" set paste       " for importing
" set cursorbind
" set debug="msg,throw,beep"
"  
"    C PROGRAMING 
" set cindent
" set cirkeys

set nocompatible
set title
set toolbar=icons,text
set visualbell

" NUMBERS
set number
set norelativenumber
set ruler
set textwidth=73 
set laststatus=0   
set icon

" TABS 
set expandtab
set tabstop=2
set softtabstop=2
set smarttab
set shiftwidth=2

" INDENT
set autoindent
set smartindent
set breakindent
set breakindentopt="min(25),shift(2)"
set indentexpr=lispindent()
set lisp " this sets the indent on RETURN during insert mode
" set indentkeys="[list of keys that automatically indent)
" 
" easier to see characters when `set paste` is on
set listchars=tab:→\ ,eol:↲,nbsp:␣,space:·,trail:·,extends:⟩,precedes:⟨

"   SWAPPING & BACKUP 
"   more risky, but cleaner
set nobackup
set noswapfile
set nowritebackup
set confirm

"    CURSOR
" center the cursor always on the screen
set scrolloff=999
" set cursorcolumn
set cursorline
set previewpopup

" SEARCH
set infercase
set smartcase
set ignorecase
set incsearch
set wildchar=F
set wildcharm
set wildignore=""
set wildmenu
set wildmode=list:lastused
set hlsearch     
" highlight search hits, remember `:noh` to clear 

" avoid most of the 'Hit Enter ...' messages
set shortmess=aoOtI

" prevents truncated yanks, deletes, etc.
set viminfo='20,<1000,s1000

let g:loaded_matchparen=1
set foldmethod=manual

set formatoptions-=B   " don't add space between two multi-byte chars in join 
set formatoptions+=1   " don't break a line after a one-letter word

" requires PLATFORM env variable set (in ~/.bashrc)
if $PLATFORM == 'mac'
  " required for mac delete to work
  set backspace=indent,eol,start
endif

" stop complaints about switching buffer with changes
set hidden
set buflisted

" command history
set history=100

" here because plugins and stuff need it
syntax enable

" allow sensing the filetype
filetype plugin on

set loadplugins
" Install vim-plug if not already installed
" (Yes I know about Vim 8 Plugins. They suck.)
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

" high contrast for streaming, etc.
set background=dark
colorscheme elflord

set modelines=10
set opendevice

" only load plugins if Plug detected
if filereadable(expand("~/.vim/autoload/plug.vim"))
  call plug#begin('~/.vimplugins')
  Plug 'vim-pandoc/vim-pandoc'
  Plug 'https://gitlab.com/rwxrob/vim-pandoc-syntax-simple'
  Plug 'cespare/vim-toml'
  Plug 'fatih/vim-go'
  Plug 'airblade/vim-gitgutter'
  Plug 'PProvost/vim-ps1'
  "Plug 'morhetz/gruvbox'
  call plug#end()
  let g:go_fmt_fail_silently = 0 " let me out even with errors
  let g:go_fmt_command = 'goimports' " autoupdate import
  let g:go_fmt_autosave = 1
else
  autocmd vimleavepre *.go !gofmt -w % " backup if fatih fails
endif

" fill in empty markdown links with duck.com search
autocmd vimleavepre *.md !perl -p -i -e 's,\[([^\]]+?)\]\(\),[\1](https://duck.com/lite?q=\1),g' %

" enable omni-completion
set omnifunc=syntaxcomplete#Complete
set complete=".,w,b,u,U,k,kspell,k{dict},s,s{tsr},-,t,i"
set completeopt="menu,preview,popup"
set completepopup

" set spell
" set dictionary="spell"
set spelllang"en_us,nl,medical"
" set spellbadword()
set spellsuggest=double
" set soundfold
set spellcapcheck
set thesaurus "https://github.com/vim/vim/issues/629#issuecomment-443293282"

" force some file names to be specific file type
"au bufnewfile,bufRead *.bash* set ft=sh
au bufnewfile,bufRead *.profile set filetype=sh
au bufnewfile,bufRead *.crontab set filetype=crontab
au bufnewfile,bufRead *ssh/config set filetype=sshconfig
au bufnewfile,bufRead *gitconfig set filetype=gitconfig
au bufnewfile,bufRead /tmp/psql.edit.* set syntax=sql

" displays all the syntax rules for current position, useful
" when writing vimscript syntax plugins
function! <SID>SynStack()
	if !exists("*synstack")
		return
	endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc  

" start at last place you were editing
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" this will print to the file comment verbosefile out to see it displayed
set verbose
set verbosefile"/tmp/vim.out"

" pane switching vi style (duh)
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" functions keys
map <F1> :set number!<CR> :set relativenumber!<CR>
nmap <F2> :call <SID>SynStack()<CR>
set pastetoggle=<F3>
map <F4> :set list!<CR>
map <F5> :set cursorline!<CR>
map <F7> :set spell!<CR>
map <F12> :set fdm=indent<CR>

" disable arrow keys (vi muscle memory)
noremap <up> :echoerr "Yeah that key doesn't do that"<CR>
noremap <down> :echoerr "Hey try the HOME ROW"<CR>
noremap <left> :echoerr "Are you STILL USING ARROWS"<CR>
noremap <right> :echoerr "
inoremap <up> <NOP>
inoremap <down> <NOP>
inoremap <left> <NOP>
inoremap <right> <NOP>


set formatoptions-=t   " don't auto-wrap text using text width
set formatoptions+=c   " autowrap comments using textwidth with leader
set formatoptions-=r   " don't auto-insert comment leader on enter in insert
set formatoptions-=o   " don't auto-insert comment leader on o/O in normal
set formatoptions+=q   " allow formatting of comments with gq
set formatoptions-=w   " don't use trailing whitespace for paragraphs
set formatoptions-=a   " disable auto-formatting of paragraph changes
set formatoptions-=n   " don't recognized numbered lists
set formatoptions+=j   " delete comment prefix when joining
set formatoptions-=2   " don't use the indent of second paragraph line
set formatoptions-=v   " don't use broken 'vi-compatible auto-wrapping'
set formatoptions-=b   " don't use broken 'vi-compatible auto-wrapping'
set formatoptions+=l   " long lines not broken in insert mode
set formatoptions+=m   " multi-byte character line break support
set formatoptions+=M   " don't add space before or after multi-byte char
" printer control settings
" set printdevice"" 
" set printencoding""
" set printexpr     " this is for printing PostScript information
" set printfont"" 
" set printheader"" " this is how to set the Header Formating
" set printoptions""      " see popt-option
" 
" read personal/private vim configuration (keep last to override)
" set rtp^=~/.vimpersonal
" set rtp^=~/.vimprivate
